Upgrade and switch to Drone 1.0.0
drone-plugins/drone-volume-cache pull request #21
Opened 2019-01-20 23:23 UTC by tboerger

2019-01-21 04:10 UTC, appleboy requested changes

2019-01-21 04:10 UTC, appleboy commented on README.md
> +[![](https://images.microbadger.com/badges/image/plugins/volume-cache.svg)](https://microbadger.com/images/plugins/volume-cache "Get your own image badge on microbadger.com")
duplicate of the badge in the bottom.

2019-01-21 22:19 UTC, techknowlogick approved these changes

2019-01-22 06:32 UTC, appleboy approved these changes

2019-01-23 10:10 UTC, merged